#!/usr/bin/python3

import requests
import json

def getLocation():
    print("-------------------------------------")
    ip = input("> ") 

    url = ' https://geolocation-db.com/jsonp/' + ip

    response = requests.get(url)
    result = response.content.decode()
    result = result.split("(")[1].strip(")")
    result  = json.loads(result)

    print("-------------------------------------")
    print("[+]country code =", result["country_code"])
    print("[+]country name =", result["country_name"])
    print("[+]city =", result["city"])
    print("[+]postal =", result["postal"])
    print("[+]latitude =", result["latitude"])
    print("[+]longitude =", result["longitude"])
    print("[+]IPv4 =", result["IPv4"])
    print("[+]state =", result["state"])



def main():
    try:
        getLocation()
    except KeyboardInterrupt:
        print("\n-------------------------------------")
        exit(0)


main()
