#!/usr/bin/python3

import requests
import json


def location():
    url = 'https://ipinfo.io/json'
    response = requests.get(url)

    if response.status_code != 200:
        print(f"[-] Faied to get ip: {status_code}")
        
        exit()
    else:
        data = response.json()
        print("PUBLIC IP INFO:")
        print("---------------------")
        print(f"[+]ip = {data['ip']}\n[+]city = {data['city']}\n[+]region = {data['region']}\n[+]timezone = {data['timezone']}")
        


location()
