#!/usr/bin/python3

import requests
from  bs4 import BeautifulSoup

url = 'https://ipinfo.io/json'
dnsLeakUrl = 'https://www.dnsleaktest.com/'

def location():

    try:
        response = requests.get(url)
        if response.status_code != 200:
            print(f"[-] Faied to get ip: {response.status_code}")
        else:
            data = response.json()
            print("\nPUBLIC IP INFO:")
            print("---------------------")
            print(f"[+]ip = {data['ip']}\n[+]city = {data['city']}\n[+]region = {data['region']}\n[+]timezone = {data['timezone']}")
    except:
        print(f"[-] Failed to resolve {url} ")
        exit()


def dnsLeakTest():

    try:
        response = requests.get(dnsLeakUrl)
        if response.status_code != 200:
            print(f"[-] Faied to get ip: {response.status_code}")
        else:
            print("\nDNS LEAK INFO:")
            print("---------------------")
            soup = BeautifulSoup(response.text, 'html.parser')
            hello_paragraph = soup.find('p', class_='hello text-2xl font-bold')
            text_lg_paragraph = soup.find('p', class_='text-lg')
            if hello_paragraph:
                print(hello_paragraph.get_text(strip=True))

            if text_lg_paragraph:
                print(text_lg_paragraph.get_text(strip=True))

            print("\n")

    except:
        print(f"[-] Failed to resolve {dnsLeakUrl} ")
        exit()



location()
dnsLeakTest()
